// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by LogCategoryGenerator
// To add new categories, use Tools -> Logger -> Category Manager

namespace Azen.Logger
{
    public enum LogCategory
    {
        None = 0,
        Analytics = 1,
        Audio = 2,
        Error = 3,
        Gameplay = 4,
        Input = 5,
        Network = 6,
        Other = 7,
        Performance = 8,
        PMG = 9,
        System = 10,
        UI = 11,
        Warning = 12,
    }
}
